hackerboard/config/routes.rb
Hackerboard::Application.routes.draw do
  # scope '/:locale' do
  root to: 'questions#index'

  namespace :admin do
    resources :categories do
      member do
        get :remove
      end
    end
  end

  controller :feed do
    get '/feed/questions/:id', action: :replies, as: :replies_feed
    get '/feed/questions', action: :questions, as: :questions_feed
    get '/feed/categories/:id', action: :categories, as: :categories_feed
  end

  controller :users do
    get '/signup', action: :new
    post '/signup', action: :create
    get '/users/:id', action: :show, as: :user
  end

  controller :categories do
    get '/category/:id', action: :show, as: :category
  end

  controller :sessions do
    get '/login', action: :new
    post '/login', action: :create
    get '/logout', action: :destroy
  end

  controller :questions do
    get '/questions', action: :index, as: :questions
    get '/questions/new', action: :new, as: :new_question
    post '/questions/new', action: :create
    get '/questions/search', action: :search, as: :search_questions
    get 'questions/:id', action: :show, as: :question
  end

  controller :replies do
    post '/questions/:question_id/replies/new', action: :create, as: :new_reply
  end
  # end
end

hackerboard/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions, dependent: :destroy

  validates_presence_of :name

  scope :sorted_by_name, order("name asc")

  default_scope where(deleted_at: nil)

  def self.to_be_removed
    unscoped.where("deleted_at is not null")
  end

  def remove!
    update_column(:deleted_at, Time.now)
  end
end

hackerboard/app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < AdminController
    layout "window"

    def index
      @categories = Category.all
    end

    def remove
      @category = Category.find(params[:id])
    end

    def edit
      @category = Category.find(params[:id])
    end

    def destroy
      @category = Category.find(params[:id])
      @category.remove!
      redirect_to admin_categories_path, notice: 'Categoria deletada com sucesso!'
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to admin_categories_path, notice: 'Categoria criada com sucesso!'
      else
        render :new
      end
    end

    def update
      @category = Category.find(params[:id])

      if @category.update(category_params)
        redirect_to admin_categories_path, notice: 'Categoria atualizada com sucesso!'
      else
        render :edit, id: @category.id
      end
    end

    private

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

hackerboard/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    render text: "WIP"
  end
end

hackerboard/app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

hackerboard/app/views/admin/categories/edit.html.erb
<%= render "form", category: @category %>

hackerboard/app/views/admin/categories/index.html.erb
<% @categories.each do |category| %>
  <p>
    <%= link_to category.name, edit_admin_category_path(category) %>
    <%= link_to "Remove", remove_admin_category_path(category) %>
  </p>
<% end %>

<p>
  <%= link_to "Add category", new_admin_category_path %>
</p>

hackerboard/app/views/admin/categories/new.html.erb
<%= render "form", category: @category %>

hackerboard/app/views/admin/categories/remove.html.erb
<p>
  Você quer mesmo remover <strong><%= @category.name %></strong>?
  <br>
  Não será possivel desfazer essa ação.
</p>

<%= button_to "sim", admin_category_path(@category), method: :delete %>