hackerboard/config/routes.rb
Hackerboard::Application.routes.draw do
  # scope '/:locale' do
  root to: 'questions#index'

  namespace :admin do
    resources :categories do
      member do
        get :remove
      end
    end
  end

  controller :feed do
    get '/feed/questions/:id', action: :replies, as: :replies_feed
    get '/feed/questions', action: :questions, as: :questions_feed
    get '/feed/categories/:id', action: :categories, as: :categories_feed
  end

  controller :users do
    get '/signup', action: :new
    post '/signup', action: :create
    get '/users/:id', action: :show, as: :user
  end

  controller :categories do
    get '/category/:id', action: :show, as: :category
  end

  controller :sessions do
    get '/login', action: :new
    post '/login', action: :create
    get '/logout', action: :destroy
  end

  controller :questions do
    get '/questions', action: :index, as: :questions
    get '/questions/new', action: :new, as: :new_question
    post '/questions/new', action: :create
    get '/questions/search', action: :search, as: :search_questions
    get 'questions/:id', action: :show, as: :question
  end

  controller :replies do
    post '/questions/:question_id/replies/new', action: :create, as: :new_reply
  end
  # end
end

hackerboard/app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  belongs_to :question, counter_cache: true

  validates_presence_of :question, :user, :body

  scope :to_feed, includes(:user).limit(10).order("id desc")
end

hackerboard/app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  require_logged_user

  def create
    @question = Question.find(params[:question_id])
    @reply = current_user.replies.new(reply_params)
    @reply.question = @question

    if @reply.save
      flash[:notice] = t('flash.replies.create.notice')
    else
      flash[:alert] = t('flash.replies.create.alert')
    end

    redirect_to question_path(@question)
  end

  private

  def reply_params
    params.require(:reply).permit(:body, :question_id)
  end
end

hackerboard/app/views/replies/_form.html.erb
<%= form_for reply, url: new_reply_path(question) do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

hackerboard/app/views/replies/_reply.html.erb
<div class="reply">
  <p class="about">
    <%= profile_link(reply.user) %>
    <%= t("reply.about", time: l(reply.created_at, format: :short)) %>
  </p>

  <%= simple_format reply.body %>
</div>

hackerboard/app/views/replies/_require_login.html.erb
<p class="require-login">
  <%= t('reply.need_to_be_logged') %>
</p>  